version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=canvas
      - POSTGRES_DB=canvas_production
    networks:
      - canvas

  canvas:
    container_name: canvas
    build:
      context: .
      dockerfile: canvas.dockerfile
    depends_on:
      - postgres
    ports:
      - "443:443"
      - "8080:80"
    networks:
      - canvas

networks:
  canvas: {}

