FROM ruby:3.1.0

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y && \
    apt install -y software-properties-common zlib1g-dev libxml2-dev libsqlite3-dev postgresql libpq-dev libxmlsec1-dev libyaml-dev libidn11-dev curl make g++ libcurl4-openssl-dev ruby-dev vim nano git && \
    gem install passenger -v 6.0.20 && \
    passenger-install-nginx-module && \
    apt clean

WORKDIR /var/www/canvas

RUN git clone --branch prod --depth 1 https://github.com/instructure/canvas-lms.git . && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
    apt-get install -y nodejs && \
    gem install bundler --version 2.4.19 && \
    bundle config set --local path vendor/bundle && \
    bundle install && \
    npm install -g yarn && \
    yarn install && \
    apt clean

ARG COMPILE_ASSETS_BRAND_CONFIGS=0 
ENV RAILS_ENV=production

# Compilar assets
RUN mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands && \
    touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss && \
    touch Gemfile.lock && \
    touch log/production.log && \
    bundle exec rake canvas:compile_assets

ENV CANVAS_LMS_ADMIN_EMAIL=example@example.com
ENV CANVAS_LMS_ADMIN_PASSWORD=adminadmin
ENV CANVAS_LMS_ACCOUNT_NAME=example
ENV CANVAS_LMS_STATS_COLLECTION=3

# Crear certificado SSL
RUN mkdir /opt/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /opt/nginx/ssl/canvas.key -out /opt/nginx/ssl/canvas.crt -subj "/C=''/ST=''/L=''/O=''/CN=''"

# Crear carpeta para logs
RUN chmod o+x /root && \
    gem install base64 -v 0.2.0 && \
    gem install stringio -v 3.1.0 && \
    chmod 777 /var/www/canvas/log/production.log

# Crear carpeta para archivos temporales
RUN mkdir -p /var/www/canvas/tmp/files && \
    chmod 777 /var/www/canvas/tmp/files && \
    mkdir -p /tmp/attachment_fu && \
    chmod 777 /tmp/attachment_fu

RUN gem install rails -v 7.1.3

RUN apt install python3 && \
    curl https://bootstrap.pypa.io/get-pip.py | python3 && \
    pip install lxml && \
    git clone https://github.com/instructure/QTIMigrationTool.git vendor/QTIMigrationTool && \
    chmod +x vendor/QTIMigrationTool/migrate.py

COPY ./config/* config/

COPY ./canvas.conf /opt/nginx/conf/nginx.conf
COPY ./script.sh /root/script.sh

RUN chmod +x /root/script.sh

CMD [ "/root/script.sh" ]
