#!/bin/bash

eval "$(rbenv init -)"
RAILS_ENV=production

cd /var/www/canvas && \
gem install bundler --version 2.4.19 && \
bundle config set --local path vendor/bundle && \
bundle install

# Comando original
original_command="bundle exec rake db:initial_setup"

# Intentar ejecutar el comando original
$original_command

# Verificar si el comando original falló
if [ $? -ne 0 ]; then
    # Acciones a realizar en caso de fallo

    # Mover archivos
    echo "Mover archivos"
    mv db/migrate/20210823222355_change_immersive_reader_allowed_on_to_on.rb .
    mv db/migrate/20210812210129_add_singleton_column.rb db/migrate/20111111214311_add_singleton_column.rb

    # Ejecutar yarn gulp rev
    echo "Ejecutar yarn gulp rev"
    yarn gulp rev

    # Ejecutar el comando original nuevamente
    echo "Ejecutar el comando original nuevamente"
    bundle exec rake db:initial_setup

    # Mover el archivo de vuelta
    echo "Mover el archivo de vuelta"
    mv 20210823222355_change_immersive_reader_allowed_on_to_on.rb db/migrate/.

    # Ejecutar rake db:migrate
    echo "Ejecutar rake db:migrate"
    bundle exec rake db:migrate
fi

mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands && \
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss && \
touch Gemfile.lock && \
touch log/production.log && \
bundle exec rake canvas:compile_assets

# Crear certificado SSL
mkdir /opt/nginx/ssl
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /opt/nginx/ssl/canvas.key -out /opt/nginx/ssl/canvas.crt -subj "/C=''/ST=''/L=''/O=''/CN=''"

# Crear carpeta para logs
chmod o+x /root
gem install base64 -v 0.2.0
gem install stringio -v 3.1.0
chmod 777 /var/www/canvas/log/production.log
chmod 777 /root/.rbenv/shims/ruby

# Crear carpeta para archivos temporales
mkdir -p /var/www/canvas/tmp/files
chmod 777 /var/www/canvas/tmp/files
chmod 777 /tmp/attachment_fu

# Iniciar nginx
/opt/nginx/sbin/nginx

# Iniciar canvas
echo "canvas is running..."
tail -f /var/www/canvas/log/production.log
