# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: postgres
  username: canvas
  password: admin
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: postgres
  username: canvas
  password: admin
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: postgres
  username: canvas
  password: admin
  timeout: 5000
